export const GET_GAMES = "GET_GAMES";
export const GET_GAME_DETAILS = "GET_GAME_DETAILS";
export const ADD_WHISHLIST = "ADD_WHISHLIST";
export const SET_FILTERS = "SET_FILTERS";
export const RESET_FILTERS = "RESET_FILTERS";
export const SET_PAGINATION = "SET_PAGINATION";
export const CHANGE_PAGE = "CHANGE_PAGE";
